services:
  - type: web
    name: hayati
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: hayati-db
          property: connectionString

databases:
  - name: hayati-db
    plan: free
    databaseName: hayati
